name: Build Test
on:
  push:
    branches-ignore:
      - "master"

jobs:
  build:
    runs-on: ubuntu-20.04

    name: Build

    steps:
      - uses: actions/checkout@v2

      - uses: olafurpg/setup-scala@v12
        name: Setup Scala

      - uses: actions/setup-node@v2
        name: Setup Node 14
        with:
          node-version: '14'

      - uses: japgolly/setup-scalajs@v1
        name: Setup Scala.js

      - name: Run SBT Build
        run: sbt build
